# Generated by Django 4.0.4 on 2022-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readlists', '0002_view_list_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='icon',
            field=models.TextField(default='bookmark'),
        ),
    ]
