# Generated by Django 4.0.4 on 2022-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowChangeAvatar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowWriteComments',
            field=models.BooleanField(default=True),
        ),
    ]
