# Generated by Django 3.2.3 on 2022-05-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='photoUrl',
            field=models.TextField(null=True),
        ),
    ]
