# Generated by Django 3.2.3 on 2022-05-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='disableComments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hideLikes',
        ),
    ]
