# Generated by Django 3.2.3 on 2022-06-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20220514_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='framework',
            field=models.BooleanField(default=True),
        ),
    ]
