# Generated by Django 4.0.4 on 2022-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hideDate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='hideLikes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='restrictComments',
            field=models.BooleanField(default=False),
        ),
    ]
