# Generated by Django 4.0.4 on 2022-06-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_hidedate_article_hidelikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
