# Generated by Django 4.0.4 on 2022-06-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hideAuthor',
        ),
    ]
