# Generated by Django 3.2.3 on 2022-06-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_aditionalarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aditionalarticle',
            old_name='shareArticle',
            new_name='sharedArticle',
        ),
    ]
