# Generated by Django 3.2.3 on 2022-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_sharearticle_aditionalarticle_sharedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coverImageMedium',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='coverImageSmall',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
