# Generated by Django 3.2.3 on 2022-07-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20220622_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='coverImageMedium',
        ),
        migrations.RemoveField(
            model_name='article',
            name='coverImageSmall',
        ),
    ]
